<?php

namespace App\Http\Requests;

use Auth;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\JsonResponse;
use Illuminate\Validation\ValidationException;


class UserRegisterationRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name'=>'required',
            'email'=>'bail|required|email|unique:users',
            'password'=>'required|min:6'
        ];
    }
    public function messages()
    {
        return array_merge(parent::messages(),
        [
            'email.unique:users'=>'Email is already registered.'
        ]
        ); // TODO: Change the autogenerated stub
    }
    public function failedValidation($validator)
    {
        $response = new JsonResponse(
            array_merge(['status' => false,],$validator->errors()->toArray()), 422);

        throw new ValidationException($validator, $response);
    }
}
